# Generated by Django 4.1.3 on 2022-12-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking_system', '0002_comment_active_contributor_active_issue_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Ecriture', 'Ecriture')], max_length=200),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(blank=True, choices=[('Author', 'Author'), ('Manager', 'Manager'), ('Creator', 'Creator')], max_length=200),
        ),
    ]
