# Generated by Django 4.1.3 on 2022-12-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking_system', '0003_alter_contributor_permission_alter_contributor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('Lecture', 'read'), ('Ecriture', 'write'), ('Modification / Suppression', 'update_and_delete')], max_length=200),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(blank=True, choices=[('Author', 'author'), ('Manager', 'manager'), ('Creator', 'creator')], max_length=200),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('Faible', 'small'), ('Moyenne', 'medium'), ('Élevée', 'high')], max_length=128),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('À faire', 'to_do'), ('En cours', 'on_progress'), ('Terminé', 'done')], max_length=128),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('Bug', 'bug'), ('Amélioration', 'ameliorate'), ('Tâche', 'task')], max_length=128),
        ),
    ]
