# Generated by Django 4.1.3 on 2022-12-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking_system', '0004_alter_contributor_permission_alter_contributor_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
