# Generated by Django 4.1.3 on 2022-12-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracking_system', '0005_alter_contributor_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='author_user',
            new_name='author_user_id',
        ),
    ]
